# Generated by Django 5.1.4 on 2024-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="hints",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
